name: Run Tests with Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest   # O puedes cambiarlo a 'windows-latest' o 'macos-latest' según sea necesario

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # O la versión de Python que estés usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   # Asegúrate de tener un archivo requirements.txt con pytest como dependencia

      - name: Run tests with pytest
        run: |
          pytest
